version: "3.9"

networks:
  web:
    external: true  # Create with: docker network create web

volumes:
  db_data:
  letsencrypt:

services:
  # ============ TRAEFIK (Main Reverse Proxy + HTTPS) ============
  traefik:
    image: traefik:v3.0
    command:
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.le.acme.tlschallenge=true"
      - "--certificatesresolvers.le.acme.email=muneebusmani8355@gmail.com"
      - "--certificatesresolvers.le.acme.storage=/letsencrypt/acme.json"
      - "--api.dashboard=true"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "letsencrypt:/letsencrypt"
    networks:
      - web
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik-dashboard.rule=Host(`logs.enginesmarket.co.uk`)"
      - "traefik.http.routers.traefik-dashboard.entrypoints=websecure"
      - "traefik.http.routers.traefik-dashboard.tls.certresolver=le"
      - "traefik.http.services.traefik-dashboard.loadbalancer.server.port=80"

  # ============ MAIN SITE (Next.js App) ============
  webapp:
    build: ./website
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.webapp.rule=Host(`enginesmarket.co.uk`)"
      - "traefik.http.routers.webapp.entrypoints=websecure"
      - "traefik.http.routers.webapp.tls.certresolver=le"
      # HTTP → HTTPS redirect
      - "traefik.http.routers.webapp-http.rule=Host(`enginesmarket.co.uk`)"
      - "traefik.http.routers.webapp-http.entrypoints=web"
      - "traefik.http.routers.webapp-http.middlewares=to-https"
      - "traefik.http.middlewares.to-https.redirectscheme.scheme=https"
      # App runs on port 3000
      - "traefik.http.services.webapp.loadbalancer.server.port=3000"
    networks:
      - web
    restart: unless-stopped

  # ============ MYSQL (WordPress & phpMyAdmin DB) ============
  db:
    image: mysql:8.0
    container_name: wordpress-db
    restart: always
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - web
    # Don't expose to outside

  # ============ WORDPRESS (PHP-FPM) ============
  wordpress:
    image: wordpress:php8.2-fpm
    container_name: wordpress
    restart: always
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_CONFIG_EXTRA: |
        define('WP_MEMORY_LIMIT', '512M');
        define('WP_MAX_MEMORY_LIMIT', '1024M');
        define('DISALLOW_FILE_MODS', false);
        define('WP_HOME', 'https://cms.enginesmarket.co.uk');
        define('WP_SITEURL', 'https://cms.enginesmarket.co.uk');
    volumes:
      - ./cms:/var/www/html
      - ./php.ini:/usr/local/etc/php/conf.d/custom.ini
    networks:
      - web

  # ============ NGINX (for WordPress, only internally) ============
  wordpress-nginx:
    image: nginx:alpine
    container_name: wordpress-nginx
    restart: always
    volumes:
      - ./cms:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.wordpress.rule=Host(`cms.enginesmarket.co.uk`)"
      - "traefik.http.routers.wordpress.entrypoints=websecure"
      - "traefik.http.routers.wordpress.tls.certresolver=le"
      - "traefik.http.services.wordpress.loadbalancer.server.port=80"
    depends_on:
      - wordpress

  # ============ PHPMYADMIN ============
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    restart: always
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: root
      # Fix for PathPrefix
      PMA_ABSOLUTE_URI: https://pma.enginesmarket.co.uk/
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.pma.rule=Host(`pma.enginesmarket.co.uk`)"
      - "traefik.http.routers.pma.entrypoints=websecure"
      - "traefik.http.routers.pma.tls.certresolver=le"
      - "traefik.http.services.pma.loadbalancer.server.port=80"
    networks:
      - web
    depends_on:
      - db
