import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import AOSInit from "@/components/AOSInit"; // Import the client component
import { Toaster } from "sonner";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="antialiased bg-white" suppressHydrationWarning>
        <Toaster richColors />
        <AOSInit /> {/* Initialize AOS on the client */}
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
